// scripts/deploy.js
// Deploys TimberSupplyChain to the configured network and writes
// contract-config.json at the project root for use by the listener and frontend.

const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();

  console.log("=".repeat(60));
  console.log("Deploying TimberSupplyChain");
  console.log("Network:  ", (await ethers.provider.getNetwork()).name);
  console.log("Deployer: ", deployer.address);
  console.log(
    "Balance:  ",
    ethers.formatEther(await ethers.provider.getBalance(deployer.address)),
    "ETH"
  );
  console.log("=".repeat(60));

  // Deploy
  const TimberSupplyChain = await ethers.getContractFactory("TimberSupplyChain");
  const contract = await TimberSupplyChain.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("\n✅ TimberSupplyChain deployed to:", address);

  // Build the config object — address + full ABI
  const artifact = JSON.parse(
    fs.readFileSync(
      path.join(__dirname, "../artifacts/contracts/TimberSupplyChain.sol/TimberSupplyChain.json"),
      "utf8"
    )
  );

  const config = {
    address,
    abi: artifact.abi,
    network: (await ethers.provider.getNetwork()).name,
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
  };

  // Write to contracts/ directory
  const localPath = path.join(__dirname, "../contract-config.json");
  fs.writeFileSync(localPath, JSON.stringify(config, null, 2));
  console.log("📄 contract-config.json written to:", localPath);

  // Also write to project root (../contract-config.json from contracts/)
  const rootPath = path.join(__dirname, "../../contract-config.json");
  fs.writeFileSync(rootPath, JSON.stringify(config, null, 2));
  console.log("📄 contract-config.json written to project root:", rootPath);

  // Write plain JSON for the React frontend (served from public/, fetched at
  // startup — swapping this file re-points the app with no rebuild).
  const frontendPublicPath = path.join(__dirname, "../../frontend/public/contract-config.json");
  if (fs.existsSync(path.dirname(frontendPublicPath))) {
    fs.writeFileSync(frontendPublicPath, JSON.stringify(config, null, 2));
    console.log("📄 frontend/public/contract-config.json updated");
  }

  // Legacy: also write the JS-global version for the old static frontend, if
  // that directory still exists (kept in frontend-legacy/ during migration).
  const legacyJsPath = path.join(__dirname, "../../frontend-legacy/js/contract-config.js");
  const jsContent = `// Auto-generated by deploy.js — do not edit manually\nconst CONTRACT_CONFIG = ${JSON.stringify(config, null, 2)};\n`;
  if (fs.existsSync(path.dirname(legacyJsPath))) {
    fs.writeFileSync(legacyJsPath, jsContent);
    console.log("📄 frontend-legacy/js/contract-config.js updated");
  }

  console.log("\n📋 Next steps:");
  console.log("  1. Copy the address above into listener/.env → CONTRACT_ADDRESS=", address);
  console.log("  2. Copy the address into backend/application.properties → contract.address=", address);
  console.log("  3. Verify on Etherscan (optional):");
  console.log("     npx hardhat verify --network sepolia", address);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("❌ Deployment failed:", err);
    process.exit(1);
  });
